from datetime import datetime
from .analysis import compute_all_scores

RISK_LABELS = {"low": "低", "info": "信息", "medium": "中", "high": "高"}

def generate_markdown(domain, results, elapsed):
    scores = compute_all_scores(results)
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    lines = [f"# RECON — {domain}", "", f"{now} · {elapsed:.1f}s", ""]
    lines.append("## 总体健康度")
    for key, label in [("overall","总体"),("security","安全"),("infrastructure","基础设施"),("email","邮件"),("techdebt","技术债")]:
        s = scores.get(key, 0)
        lines.append(f"- {label}: {s}/100")
    lines.append("")
    for m, d in results.items():
        fs = d.get("findings", []); infs = d.get("inferences", [])
        if not fs and not infs: continue
        lines.append(f"## {m}")
        for f in fs: lines.append(f"- **{f.get('label')}**: {f.get('value')} [{RISK_LABELS.get(f.get('risk'), f.get('risk'))}]")
        for i in infs: lines.append(f"  > {i}")
        lines.append("")
    lines.append("---\n*Generated by RECON Passive Recon CLI*")
    return "\n".join(lines)
